name: CI Pipeline

# Trigger on pushes to the 'main' branch
on:
  push:
    branches: [main]

jobs:
  build:
    # Run on the latest Ubuntu runner
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        # Use a stable, widely supported version (v4)
        uses: actions/checkout@v4
      
      - name: Set up Node.js 16
        # Use a stable, widely supported version (v4)
        uses: actions/setup-node@v4
        with:
          node-version: 16
      
      - name: Install dependencies (npm install)
        run: npm install

      - name: Run tests (npm test)
        run: npm test
